### ISSUE TITLE
Error: permission denied for foreign table mydata01 (SQLSTATE 42501)

### ISSUE THREAD

**Issue by tryweb** [turbot/steampipe-plugin-googlesheets#17]
**Describe the bug**
1. Google spreadsheets has been granted editor permission
2. select can successfully read data
3. Using insert syntax shows SQLSTATE 42501

**Steampipe version (`steampipe -v`)**
0.12.2
steampipe version 0.12.2

**Plugin version (`steampipe plugin list`)**
0.1.1
hub.steampipe.io/plugins/turbot/googlesheets@latest | 0.1.1   | googlesheets 

**To reproduce**
insert into mydata01 values('V2.0', 'Jonathan Tsai', 'Assigned', '3');
Error: permission denied for foreign table mydata01 (SQLSTATE 42501)

**Expected behavior**
Unable to execute the insert syntax

**Additional context**
Does the current version only support select syntax and not implement insert/update/delete yet?

**Comment by e-gineer** [comment]
Currently Steampipe is focused on read only access only, so insert, update and delete operations are not supported.

**Comment by tryweb** [comment]
Thank you very much for your efforts. Hope to support insert, update, delete functions in the future.
