### ISSUE TITLE
SQLSTATE 42P01 will appear when the Sheet name is capitalized

### ISSUE THREAD

**Issue by tryweb** [turbot/steampipe-plugin-googlesheets#18]
**Describe the bug**
1. Sheet name includes uppercase Exp. MYDATA02 or MyData02
2. Execute the select syntax, it will appear relation does not exist

**Steampipe version (`steampipe -v`)**
0.12.2

**Plugin version (`steampipe plugin list`)**
0.1.1

**To reproduce**
```
> select title from googlesheets_sheet;
+----------+
| title    |
+----------+
| MYDATA02 |
| mydata01 |
| config   |
+----------+
> select * from MYDATA02;
Error: relation "mydata02" does not exist (SQLSTATE 42P01)
```

**Expected behavior**

**Additional context**

**Comment by e-gineer** [comment]
Hi @tryweb ... Thanks for using Steampipe!

If your table includes capital letters then the identifier needs to be quoted in Postgres. Please try:

    select * from "MYDATA02"

I think our docs could highlight this more clearly.

**Comment by tryweb** [comment]
Thanks for your quick reply, After adding quotes it works.
