### ISSUE TITLE
Getting error `'PluginTables' had unhandled error: runtime error: invalid memory address or nil pointer dereference` when `spreadsheet_id` is empty

### ISSUE THREAD

**Issue by Subhajit97** [turbot/steampipe-plugin-googlesheets#6]
**Describe the bug**
If `spreadsheet_id` is not defined in config, it is failing with following error
`Error: failed to start plugin 'googlesheets': failed to plugin initialise plugin 'steampipe-plugin-googlesheets': TableMapFunc 'PluginTables' had unhandled error: runtime error: invalid memory address or nil pointer dereference`

**Steampipe version (`steampipe -v`)**
Example: v0.9.1

**Plugin version (`steampipe plugin list`)**
Example: v0.0.1

**To reproduce**
Comment/ Remove `spreadsheet_id` from config, and try to run `steampipe query`

**Expected behavior**
Error message should be something like `spreadsheet_id must be configured.`

**Additional context**

**Comment by judell** [comment]
I'm having the same result, but not because `spreadsheet_id` is empty. Have yet to find a success path through the configuration maze, will try to add logging to figure it out.
